apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medical-app-production
  namespace: platform
spec:
  project: default
  source:
    # Wskazujemy Twoje oficjalny repozytorium na GitHubie
    repoURL: 'https://github.com/antonjuerg/20260519'
    targetRevision: HEAD
    path: k3s/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
