apiVersion: v1
kind: Service
metadata:
  name: medical-app
  namespace: app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: medical-app
  type: ClusterIP
